[book]
title = "The Making of a Modern-Day Polymath"
authors = ["Ben Moataz"]
language = "en"
src = "book"

[build]
build-dir = "public"

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]
